import type { WidgetDefinition } from "@/lib/core/types";

export const WIDGET_REGISTRY: WidgetDefinition[] = [
  {
    id: "gift-goal",
    name: "Gift Goal",
    emoji: "🎁",
    description: "เป้าหมายของขวัญ เช่น Rose 0/100",
    category: "alert",
    requiredPlan: "trial",
    path: "/widget/gift-goal",
    testEvent: "test-goal",
    resetEvent: "reset-goal",
    enabled: true,
  },
  {
    id: "magic-lantern",
    name: "Magic Lantern",
    emoji: "🧙",
    description: "ของขวัญลอยสะสมในโคมเวทมนตร์",
    category: "animation",
    requiredPlan: "trial",
    path: "/widget/magic-lantern",
    testEvent: "test-lantern",
    resetEvent: "reset-lantern",
    enabled: true,
  },
  {
    id: "gift-vehicle",
    name: "Gift Vehicle",
    emoji: "🛺",
    description: "รถวิ่งผ่านบนพรมกุหลาบ",
    category: "animation",
    requiredPlan: "trial",
    path: "/widget/gift-vehicle",
    testEvent: "test-vehicle",
    resetEvent: "reset-vehicle",
    enabled: true,
  },
  {
    id: "gift-basket",
    name: "Gift Basket",
    emoji: "🧺",
    description: "ของขวัญตกลงตะกร้าและกองสะสมบนจอ",
    category: "animation",
    requiredPlan: "trial",
    path: "/widget/gift-plane",
    testEvent: "test-basket",
    resetEvent: "reset-basket",
    enabled: true,
  },
  {
    id: "fortune-stick",
    name: "Fortune Stick",
    emoji: "🙏",
    description: "ส่งของขวัญ 99 เหรียญขึ้นไป เพื่อรับคำทำนาย",
    category: "fortune",
    requiredPlan: "trial",
    path: "/widget/fortune-stick",
    testEvent: "test-fortune",
    resetEvent: "reset-fortune",
    enabled: true,
  },
  {
    id: "evolution-pet",
    name: "Evolution Pet",
    emoji: "🐱",
    description: "สัตว์เลี้ยงโตตามจำนวนของขวัญ",
    category: "pet",
    requiredPlan: "premium",
    path: "/widget/pet",
    testEvent: "test-pet",
    resetEvent: "reset-pet",
    enabled: false,
    comingSoon: true,
  },
];

export function getWidgetById(id: string) {
  return WIDGET_REGISTRY.find((widget) => widget.id === id);
}
