import type { WidgetDefinition } from "@/lib/core/types";

export const WIDGET_REGISTRY: WidgetDefinition[] = [
  {
    id: "gift-goal",
    name: "Gift Goal",
    emoji: "🎁",
    description: "Display a live gift goal for your audience.",
    category: "alert",
    requiredPlan: "free",
    path: "/widget/gift-goal",
    testEvent: "test-goal",
    resetEvent: "reset-goal",
    enabled: true,
  },
  {
    id: "magic-lantern",
    name: "Magic Lantern",
    emoji: "🧙",
    description: "Collect gifts inside a magical lantern animation.",
    category: "animation",
    requiredPlan: "creator",
    path: "/widget/magic-lantern",
    testEvent: "test-lantern",
    resetEvent: "reset-lantern",
    enabled: true,
  },
  {
    id: "gift-vehicle",
    name: "Gift Vehicle",
    emoji: "🛺",
    description: "A themed vehicle drives across your live with gift effects.",
    category: "animation",
    requiredPlan: "creator",
    path: "/widget/gift-vehicle",
    testEvent: "test-vehicle",
    resetEvent: "reset-vehicle",
    enabled: true,
  },
  {
    id: "gift-basket",
    name: "Gift Basket",
    emoji: "🧺",
    description: "Watch gifts fall into a basket and stack on screen.",
    category: "animation",
    requiredPlan: "creator",
    path: "/widget/gift-plane",
    testEvent: "test-basket",
    resetEvent: "reset-basket",
    enabled: true,
  },
  {
    id: "fortune-stick",
    name: "Fortune Stick",
    emoji: "🙏",
    description: "View a fortune after sending a qualifying gift.",
    category: "fortune",
    requiredPlan: "creator",
    path: "/widget/fortune-stick",
    testEvent: "test-fortune",
    resetEvent: "reset-fortune",
    enabled: true,
  },
  {
    id: "evolution-pet",
    name: "Evolution Pet",
    emoji: "🐱",
    description: "A virtual pet that evolves based on gift activity.",
    category: "pet",
    requiredPlan: "creator",
    path: "/widget/pet",
    testEvent: "test-pet",
    resetEvent: "reset-pet",
    enabled: false,
    comingSoon: true,
  },
];

export function getWidgetById(id: string) {
  return WIDGET_REGISTRY.find((widget) => widget.id === id);
}